// TODO: Create a function that returns the license link
// If there is no license, return an empty string
function generateLicenseLink(license, username) {
  const year = new Date().getFullYear();
  switch (license) {
    case 'MIT':
      return {
        text: `[The MIT License](https://mit-license.org/)
      
Copyright © ${year} ${username}

Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`,
        badge: `[mit](https://img.shields.io/badge/License-mit-blue)`,
      };

    case 'Academic Free License v3.0':
      return {
        text: `[Academic Free License v3.0](https://opensource.org/licenses/AFL-3.0)`,
        badge: `[afl3.0](https://img.shields.io/badge/License-afl3.0-blue)`,
      };

    case 'Apache License 2.0':
      return {
        text: `[Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0.html)

Copyright ${year} ${username}

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.`,
        badge: `[apache-2.0](https://img.shields.io/badge/License-apache-2.0-blue)`,
      };

    case 'Artistic License 2.0':
      return {
        text: `[Artistic License 2.0](https://opensource.org/licenses/Artistic-2.0)`,
        badge: `[artistic-2.0](https://img.shields.io/badge/License-artistic-2.0-blue)`,
      };

    case 'Boost Software License 1.0':
      return {
        text: `[Boost Software License 1.0](https://www.boost.org/users/license.html)
      
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute, and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the Software is furnished to do so, all subject to the following:

The copyright notices in the Software and this entire statement, including the above license grant, this restriction and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all derivative works of the Software, unless such copies or derivative works are solely in the form of machine-executable object code generated by a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.`,
        badge: `[bsl-1.0](https://img.shields.io/badge/License-bsl-1.0-blue)`,
      };

    case 'BSD 2-claus "Simplified" License':
      return {
        text: `[BSD 2-claus "Simplified" License](https://choosealicense.com/licenses/bsd-2-clause/)

Copyright (c) ${year}, ${username}
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)  RISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`,
        badge: `[bsd-2-clause](https://img.shields.io/badge/License-bsd-2-clause-blue)`,
      };

    case 'BSD 3-claus Clear License':
      return {
        text: `[BSD 3-claus Clear License](https://opensource.org/licenses/BSD-3-Clause)

Copyright ${year} ${username}

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.`,
        badge: `[bsd-3-clause](https://img.shields.io/badge/License-bsd-3-clause-blue)`,
      };

    case 'Creative Commons Zero v1.0 Universal':
      return {
        text: `[Creative Commons Zero v1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/legalcode)`,
        badge: `[cc0-1.0](https://img.shields.io/badge/License-cc0-1.0-blue)`,
      };

    case 'Creative Commons Attribution 4.0':
      return {
        text: `[Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/legalcode)`,
        badge: `[cc-by-4.0](https://img.shields.io/badge/License-cc-by-4.0-blue)`,
      };

    case 'Creative Commons Attribution Share Alike 4.0':
      return {
        text: `[Creative Commons Attribution Share Alike 4.0](https://creativecommons.org/licenses/by-sa/4.0/legalcode)`,
        badge: `[cc-by-sa-4.0](https://img.shields.io/badge/License-cc-by-sa-4.0-blue)`,
      };

    case 'Do What The F*ck You Want To Public License':
      return {
        text: `[Do What The F*ck You Want To Public License](http://www.wtfpl.net/about/)
      
Version 2, December 2004 

Copyright (C) 2004 Sam Hocevar <sam@hocevar.net> 

Everyone is permitted to copy and distribute verbatim or modified copies of this license document, and changing it is allowed as long as the name is changed. 

DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE 
TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION 

0. You just DO WHAT THE FUCK YOU WANT TO.`,
        badge: `[wtfpl](https://img.shields.io/badge/License-wtfpl-blue)`,
      };

    case 'Educational Community License v2.0':
      return {
        text: `[Educational Community License v2.0](https://opensource.org/licenses/ECL-2.0)`,
        badge: `[ecl-2.0](https://img.shields.io/badge/License-ecl-2.0-blue)`,
      };

    case 'Eclipse Public License 1.0':
      return {
        text: `[Eclipse Public License 1.0](https://www.eclipse.org/legal/epl-v10.html)`,
        badge: `[epl-1.0](https://img.shields.io/badge/License-epl-1.0-blue)`,
      };

    case 'Eclipse Public License 2.0':
      return {
        text: `[Eclipse Public License 2.0](https://www.eclipse.org/legal/epl-2.0/)`,
        badge: `[epl-2.0](https://img.shields.io/badge/License-epl-2.0-blue)`,
      };

    case 'European Union Public License 1.1':
      return {
        text: `[European  Union Public License 1.1](https://choosealicense.com/licenses/eupl-1.1/)`,
        badge: `[eupl-1.1](https://img.shields.io/badge/License-eupl-1.1-blue)`,
      };

    case 'GNU Affero General Public License v3.0':
      return {
        text: `[GNU Affero General Public License v3.0](https://www.gnu.org/licenses/agpl-3.0.en.html)`,
        badge: `[agpl-3.0](https://img.shields.io/badge/License-agpl-3.0-blue)`,
      };

    case 'GNU General Public License v2.0':
      return {
        text: `[GNU General Public License v2.0](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html)`,
        badge: `[gpl-2.0](https://img.shields.io/badge/License-gpl-2.0-blue)`,
      };

    case 'GNU General Public License v3.0':
      return {
        text: `[GNU General Public License v3.0](https://www.gnu.org/licenses/gpl-3.0.en.html)`,
        badge: `[gpl-3.0](https://img.shields.io/badge/License-gpl-3.0-blue)`,
      };

    case 'GNU Lesser General Public License v2.1':
      return {
        text: `[GNU Lesser General Public License v2.1](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.html)`,
        badge: `[lgpl-2.1](https://img.shields.io/badge/License-lgpl-2.1-blue)`,
      };

    case 'GNU Lesser General Public License v3.0':
      return {
        text: `[GNU Lesser General Public License v3.0](https://www.gnu.org/licenses/lgpl-3.0.en.html)`,
        badge: `[lgpl-3.0](https://img.shields.io/badge/License-lgpl-3.0-blue)`,
      };

    case 'ISC':
      return {
        text: `[ISC](https://choosealicense.com/licenses/isc/)
      
Copyright (c) ${year} ${username}

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby granted, provided that the above copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,  EGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.`,
        badge: `[isc](https://img.shields.io/badge/License-isc-blue)`,
      };

    case 'LaTeX Project Public License v1.3c':
      return {
        text: `[LaTeX Project Public License v1.3c](https://www.latex-project.org/lppl/lppl-1-3c/)`,
        badge: `[lppl-1.3c](https://img.shields.io/badge/License-lppl-1.3c-blue)`,
      };

    case 'Microsoft Public License':
      return {
        text: `[Microsoft Public License](https://opensource.org/licenses/MS-PL)`,
        badge: `[ms-pl](https://img.shields.io/badge/License-ms-pl-blue)`,
      };

    case 'Mozilla Public License 2.0':
      return {
        text: `[Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/)`,
        badge: `[mpl-2.0](https://img.shields.io/badge/License-mpl-2.0-blue)`,
      };

    case 'Open Software License 3.0':
      return {
        text: `[Open Software License 3.0](https://opensource.org/licenses/OSL-3.0)`,
        badge: `[osl-3.0](https://img.shields.io/badge/License-osl-3.0-blue)`,
      };

    case 'PostgreSQL License':
      return {
        text: `[PostgreSQL License](https://opensource.org/licenses/postgresql)

Copyright (c) ${year} ${username}

Permission to use, copy, modify, and distribute this software and its documentation for any purpose, without fee, and without a written agreement is hereby granted, provided that the above copyright notice and this paragraph and the following two paragraphs appear in all copies.

IN NO EVENT SHALL $ORGANISATION BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF $ORGANISATION HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

$ORGANISATION SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN "AS IS" BASIS, AND $ORGANISATION HAS NO OBLIGATIONS TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.`,
        badge: `[postgresql](https://img.shields.io/badge/License-postgresql-blue)`,
      };

    case 'SIL Open Font License 1.1':
      return {
        text: `[SIL Open Font License 1.1](https://opensource.org/licenses/OFL-1.1)`,
        badge: `[ofl-1.1](https://img.shields.io/badge/License-ofl-1.1-blue)`,
      };

    case 'University of Illinois/NCSA Open Source License':
      return {
        text: `[University of Illinois/NCSA Open Source License](https://opensource.org/licenses/NCSA)`,
        badge: `[ncsa](https://img.shields.io/badge/License-ncsa-blue)`,
      };

    case 'The Unlicense':
      return {
        text: `[The Unlicense](https://unlicense.org/)
      
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled binary, for any purpose, commercial or non-commercial, and by any means.

In jurisdictions that recognize copyright laws, the author or authors of this software dedicate any and all copyright interest in the software to the public domain. We make this dedication for the benefit of the public at large and to the detriment of our heirs and
successors. We intend this dedication to be an overt act of relinquishment in perpetuity of all present and future rights to this software under copyright law.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

For more information, please refer to [http://unlicense.org/](http://unlicense.org/)`,
        badge: `[unlicense](https://img.shields.io/badge/License-unlicense-blue)`,
      };

    case 'zLib License':
      return {
        text: `[zLib License](https://www.zlib.net/zlib_license.html)
      
zlib.h -- interface of the 'zlib' general purpose compression library
version 1.2.11, January 15th, 2017

Copyright (C) 1995-2017 Jean-loup Gailly and Mark Adler

This software is provided 'as-is', without any express or implied warranty. In no event will the authors be held liable for any damages arising from the use of this software.

Permission is granted to anyone to use this software for any purpose, including commercial applications, and to alter it and redistribute it freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not claim that you wrote the original software. If you use this software in a product, an acknowledgment in the product documentation would be appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.

  Jean-loup Gailly        Mark Adler
  jloup@gzip.org          madler@alumni.caltech.edu`,
        badge: `[zlib](https://img.shields.io/badge/License-zlib-blue)`,
      };
  }
}

module.exports = generateLicenseLink;
